using UnityEngine;

public class Destruible : MonoBehaviour
{
    void OnTriggerEnter2D(Collider2D colisi칩n)
    {
        Animator animador = GetComponent<Animator>();
        if (colisi칩n.gameObject.tag == "Player")
        {
            if (name == "AceiteGrande" | name == "AceitePeque침o")
            {
                animador.SetTrigger("Choque");
            }
            else
            {
                animador.SetBool("Choque", true);
            }
        }
    }

    void Update()
    {
        if (transform.position.x + GetComponentInChildren<SpriteRenderer>().bounds.size.x < Camera.main.ScreenToWorldPoint(Vector2.zero).x)
        {
            reiniciar();
        }
    }

    private void reiniciar()
    {
        if (gameObject.name != "AceiteGrande" & gameObject.name != "AceitePeque침o")
        {
            GetComponent<Animator>().SetBool("Choque", false);
        }
    }
}
